openapi: 3.0.3
info:
  title: Simple Task API
  description: A simple API for managing tasks
  version: "1.0"
servers:
  - url: 'http://localhost:3001'
paths:
  /tasks:
    get:
      summary: List all tasks
      operationId: listTasks
      responses:
        '200':
          description: An array of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTask'
      responses:
        '201':
          description: Successfully created task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
  /tasks/{taskId}:
    get:
      summary: Get a task by ID
      operationId: getTaskById
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Task not found
  /workflows:
    get:
      summary: List all workflows
      operationId: listWorkflows
      responses:
        '200':
          description: An array of workflows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workflow'
    post:
      summary: Create a new workflow
      operationId: createWorkflow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewWorkflow'
      responses:
        '201':
          description: Successfully created task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          example: "1"
        title:
          type: string
          example: "Buy groceries"
        description:
          type: string
          example: "Milk, Bread, Eggs"
        completed:
          type: boolean
          example: false
    NewTask:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: "Study for exams"
        description:
          type: string
          example: "Chapter 4,5 and 6 of math book"
    Workflow:
      type: object
      properties:
        id:
          type: string
          example: "1"
        title:
          type: string
          example: "Cook Adobo"
        description:
          type: string
          example: "All steps to cook adobo"
        completed:
          type: boolean
          example: false
    NewWorkflow:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: "Complete math homework"
        description:
          type: string
          example: "5, 6, 7 and 8 of math book"

