repos:
  - repo: https://github.com/conventional-changelog/commitlint
    rev: v15.0.0  # Use the latest commitlint version
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
