version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "${HOST_PORT_RABBIT_MQ}:15672"
  sprout-scheduler:
    build: ./
    volumes:
      - ./workflows:/app
    depends_on:
      - rabbitmq
    command: [ "python", "run_tests.py", "scheduler" ]
  sprout-runner:
    build: ./workflows
    volumes:
      - ./workflows:/app
    depends_on:
      - rabbitmq
    command: [ "python", "run_tests.py", "worker" ]