version: 1
disable_existing_loggers: true
level: DEBUG

formatters:
  simple:
    format: '%(asctime)s - %(process)d - %(threadName)s - %(levelname)s - %(module)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  debuglogfile:
    class: logging.handlers.RotatingFileHandler
    filename: "app-debug.log"
    mode: "a"
    maxBytes: 10485760
    backupCount: 3
    level: DEBUG
    formatter: simple

  logfile:
    class: logging.handlers.RotatingFileHandler
    filename: "app.log"
    mode: "a"
    maxBytes: 10485760
    backupCount: 3
    level: DEBUG
    formatter: simple

loggers:
  myapp:
    level: INFO
    handlers: [console, logfile]
    propagate: no

  debug:
    level: DEBUG
    handlers: [console, debuglogfile]
    propagate: no

root:
  level: DEBUG
  handlers: [console, logfile]
  propagate: no
