__tpl_tests_services_rest:
  client: 'rest'
  parameters:
    base_url: 'https://jsonplaceholder.typicode.com/'
    response_encoding: 'utf-8'
    "verify": True

__tpl_tests_services_graphql:
  client: 'graphql'
  parameters:
    base_url: 'https://graphql.anilist.co/'
    response_encoding: 'utf-8'
    "verify": True
