version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
  sprout:
    build: .
    volumes:
      - .:/app
    depends_on:
      - rabbitmq