example_tests_services_rest:
  client: 'rest'
  parameters:
    base_url: 'https://jsonplaceholder.typicode.com/'
    response_encoding: 'utf-8'
    "verify": True

example_tests_services_rest_generated:
  client: 'rest'
  parameters:
    base_url: 'https://jsonplaceholder.typicode.com/'
    response_encoding: 'utf-8'
    "verify": True

example_tests_services_graphql:
  client: 'graphql'
  parameters:
    base_url: 'https://graphql.anilist.co/'
    response_encoding: 'utf-8'
    "verify": True

example_features_webdriver:
  type: headless
  browser: chrome
  parameters:
    url: 'https://the-internet.herokuapp.com/'
    headless: True
  options:
    - "start-maximized"
    - "disable-extensions"
    - "no-default-browser-check"
    - "--window-size=1920,1020"
    - "--no-sandbox"
    - "--disable-gpu"
    - "--disable-dev-shm-usage"
    - "--disable-extensions"
    - "--disable-infobars"
    - "--remote-debugging-port=9222"
