example_tests_services_rest:
  client: 'rest'
  parameters:
    base_url: 'https://jsonplaceholder.typicode.com/'
    response_encoding: 'utf-8'
    "verify": True

example_tests_services_rest_generated:
  client: 'rest'
  parameters:
    base_url: 'https://jsonplaceholder.typicode.com/'
    response_encoding: 'utf-8'
    "verify": True

example_tests_services_graphql:
  client: 'graphql'
  parameters:
    base_url: 'https://graphql.anilist.co/'
    response_encoding: 'utf-8'
    "verify": True

example_features_webdriver:
  type: selenium
  browser: firefox
  parameters:
    url: 'https://the-internet.herokuapp.com/'
    headless: True
  options:
    - "--width=1920"
    - "--height=1080"
